### ISSUE TITLE
Not able to edit block after Edit button use and redirect to particular block

### ISSUE THREAD

**Issue by darekhalecki** [fortedigital/EpiContentUsage#21]

**Comment by Fifok** [comment]
@darekhalecki It seems to be done, right?

**Comment by darekhalecki** [comment]
The content versions bug that leads to the reported problems has been fixed in https://github.com/fortedigital/EpiContentUsage/pull/39

Some pages still do not open correctly in edit mode, but this is not because of  `EpiContentUsage` module.
A color picker fails to load in the demo project.
![image](https://github.com/fortedigital/EpiContentUsage/assets/39534151/06327e19-c95f-48d2-8950-d4f394879c1a)

This is out of scope, so the ticket can be closed.
